language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 8
  - 10
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq1
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install libzmq-dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
